In [1]:
import pandas as pd
import openpyxl
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.styles import PatternFill

In [2]:
file_names = [r'課題3/2022_年間売上表.xlsx', r'課題3/2023_年間売上表.xlsx']
df = pd.DataFrame()

for file_name in file_names:
    df_temp = pd.read_excel(file_name)
    df = pd.concat([df, df_temp])
    
df = pd.DataFrame(df.groupby(['商品', '売上年'], as_index=False)['金額（千円）'].sum())
df

          商品   売上年  金額（千円）
0   アロマキャンドル  2022    1710
1   アロマキャンドル  2023     900
2      コーヒー豆  2023     860
3       セッケン  2022    1300
4       セッケン  2023    1300
5       ハチミツ  2022    1860
6       ハチミツ  2023    1000
7      フライパン  2023     670
8     ワイングラス  2022     850
9     ワイングラス  2023     850
10        包丁  2022     940
11        包丁  2023     940
12        水筒  2022    1150
13        水筒  2023    1400
14        紅茶  2022    2000
15        紅茶  2023    1870

In [3]:
wb = openpyxl.Workbook()
ws = wb.active

for r in dataframe_to_rows(df, index=False, header=True):
    ws.append(r)

for rows in ws['A1:C1']:
    for cell in rows:
        cell.fill = PatternFill(patternType='solid', fgColor='F2F2F2')

wb.save('売上集計表.xlsx')